[tool.poetry]

[tool.poetry.group.test.dependencies]
pytest = "^7.3.2"
pytest-mock = "^3.10.0"
pytest-redis = "^3.0.2"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "graphorm"
description = ""
version = "0.2.0"
readme = "README.md"
authors = [{name = "ed4b816e", email = "ed4b816e@gmail.com"}]
requires-python = '>=3.10'
dependencies = [
    'redis (>=5.0.1)',
    'prettytable (>=3.8.0)',
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-mock>=3.15.1",
    "pytest-redis>=3.1.3",
]


[tool.pytest.ini_options]
asyncio_mode = "auto"
timeout = 10
log_cli = "true"

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
strict_optional = true
